version: '2'
services:
  r-api:
    image: 126574484161.dkr.ecr.ap-southeast-2.amazonaws.com/r-api:latest
    command: npm run serve
    ports:
      - '9000:9000'
    mem_limit: 128MB
    logging:
      driver: awslogs
      options:
        awslogs-group: r-api
        awslogs-region: ap-southeast-2
        awslogs-stream-prefix: r
    environment:
      - NODE_ENV=production
    # volumes:
    #   - ./dist:/r-api/dist
